### ISSUE TITLE
Update navbar buttons to be mat-buttons

### ISSUE THREAD

**Issue by InfAurora** [InfAurora/TypeScript-Projects#43]
# Description:
All buttons on the home page should have the same look and feel.
# ToDo List:
1. Replace/update existing buttons to be the angular mat-buttons
2. Login, profile, and admin buttons

# Acceptance Criteria
* All buttons have the same style (look and feel)

# Developer Notes:
* Look at home page html for an example of how to make mat-buttons

**Comment by siddhantkhariwal** [comment]
Hey, Can I fix this issue?

**Comment by InfAurora** [comment]
> Hey, Can I fix this issue?

Yea! You should be able to create a fork of this and create a pull-request

**Comment by mamohamed252** [comment]
> Hey, Can I fix this issue?

Same with you pal…how’d you find this repo and why do you want to contribute?

**Comment by siddhantkhariwal** [comment]
> > Hey, Can I fix this issue?
> 
> Yea! You should be able to create a fork of this and create a pull-request

Please assign me first, so I can fork it and start working on it.

**Comment by siddhantkhariwal** [comment]
> > Hey, Can I fix this issue?
> 
> Same with you pal…how’d you find this repo and why do you want to contribute?

Found this through the Github issues search bar. Want to contribute to it because this is an open-source project.

**Comment by mamohamed252** [comment]
> > > Hey, Can I fix this issue?
> > 
> > 
> > Same with you pal…how’d you find this repo and why do you want to contribute?
> 
> Found this through the Github issues search bar. Want to contribute to it because this is an open-source project.

Welcome to the project, please try to follow best practices and fill out PR template as you commit and push!

GG

**Comment by InfAurora** [comment]
If there is anything that can be added to the readme to better run the project, let us know! Or include it in your pull-request. I want people to be able to easily run the application and contribute.

**Comment by mamohamed252** [comment]
@siddhantkhariwal  Hey are working on this?

**Comment by siddhantkhariwal** [comment]
> @siddhantkhariwal Hey are working on this?

Yes, I'll complete it today!

**Comment by siddhantkhariwal** [comment]
Hey, @InfAurora I have made a PR. Kindly look through it and provide any feedback if needed.

**Comment by InfAurora** [comment]
> Hey, @InfAurora I have made a PR. Kindly look through it and provide any feedback if needed.

Thanks for the update! I left a change request on your PR. Once that is addressed I will merge your changes! Thanks!
