### ISSUE TITLE
Add a signup button next to the login button

### ISSUE THREAD

**Issue by InfAurora** [InfAurora/TypeScript-Projects#45]
# Description:
Create a sign up button that uses mat-button for styling

# ToDo List:
1. Create a sign up button

# Acceptance Criteria
* Sign up button should show up either, to the left or right of login button

# Developer Notes:
* This can be updated in the navbar html file

**Comment by JAYESH8011** [comment]
hey, can I work on this issue?

**Comment by InfAurora** [comment]
> hey, can I work on this issue?

Yea! You should be able to create a fork of this and create a pull-request

**Comment by mamohamed252** [comment]
> hey, can I work on this issue?

How’d you find this repo and why do you want to contribute?

**Comment by mamohamed252** [comment]
@JAYESH8011 Hey are you still working on this?

**Comment by JAYESH8011** [comment]
yes, but due to some work I am not able work on this.

**Comment by mamohamed252** [comment]
> yes, but due to some work I am not able work on this.

ok hope to see ya back on this project later!
