### ISSUE TITLE
Create signup modal/form

### ISSUE THREAD

**Issue by InfAurora** [InfAurora/TypeScript-Projects#46]
# Description:
As a user, I should be able to enter in my credentials, so that I can sign up for a new account.

# ToDo List:
1. Create modal/form for signing up a new user
2. Fields should include
   * Mobile Number or Email
   * Full name
   * Username
   * Password
3. End of the form should be a sign up button that is the same length as the form input fields
4. Should console log "Signed up" after clicking the sign up button when all fields are filled.

# Acceptance Criteria
* When clicking the sign up button in the nav bar, a modal to sign up should appear
* The sign up button in the form should console log "Signed up"

# Developer Notes:
* REQUIRES #45 to be completed before doing this task
* There should be an existing mat-dialog (modal). Look online on how to implement it

**Comment by Anna719** [comment]
Hi! Can I try myself in this project?
Thanks:)

**Comment by InfAurora** [comment]
> Hi! Can I try myself in this project?
> 
> Thanks:)

Yea! Go ahead and give it a shot. I believe issue #44 has recently been merged. I suggest looking at the commit made for that if you get stuck. It should be similar to what you'll be trying to do.
